#!/bin/bash
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6001.xml /home/koha/koha-dev/var/log/sip_6001.out /home/koha/koha-dev/var/log/sip_6001.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6002.xml /home/koha/koha-dev/var/log/sip_6002.out /home/koha/koha-dev/var/log/sip_6002.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6003.xml /home/koha/koha-dev/var/log/sip_6003.out /home/koha/koha-dev/var/log/sip_6003.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6004.xml /home/koha/koha-dev/var/log/sip_6004.out /home/koha/koha-dev/var/log/sip_6004.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6005.xml /home/koha/koha-dev/var/log/sip_6005.out /home/koha/koha-dev/var/log/sip_6005.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6006.xml /home/koha/koha-dev/var/log/sip_6006.out /home/koha/koha-dev/var/log/sip_6006.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6007.xml /home/koha/koha-dev/var/log/sip_6007.out /home/koha/koha-dev/var/log/sip_6007.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6008.xml /home/koha/koha-dev/var/log/sip_6008.out /home/koha/koha-dev/var/log/sip_6008.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6009.xml /home/koha/koha-dev/var/log/sip_6009.out /home/koha/koha-dev/var/log/sip_6009.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6010.xml /home/koha/koha-dev/var/log/sip_6010.out /home/koha/koha-dev/var/log/sip_6010.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6011.xml /home/koha/koha-dev/var/log/sip_6011.out /home/koha/koha-dev/var/log/sip_6011.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6012.xml /home/koha/koha-dev/var/log/sip_6012.out /home/koha/koha-dev/var/log/sip_6012.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6013.xml /home/koha/koha-dev/var/log/sip_6013.out /home/koha/koha-dev/var/log/sip_6013.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6014.xml /home/koha/koha-dev/var/log/sip_6014.out /home/koha/koha-dev/var/log/sip_6014.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6015.xml /home/koha/koha-dev/var/log/sip_6015.out /home/koha/koha-dev/var/log/sip_6015.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6016.xml /home/koha/koha-dev/var/log/sip_6016.out /home/koha/koha-dev/var/log/sip_6016.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6017.xml /home/koha/koha-dev/var/log/sip_6017.out /home/koha/koha-dev/var/log/sip_6017.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6018.xml /home/koha/koha-dev/var/log/sip_6018.out /home/koha/koha-dev/var/log/sip_6018.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6019.xml /home/koha/koha-dev/var/log/sip_6019.out /home/koha/koha-dev/var/log/sip_6019.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6020.xml /home/koha/koha-dev/var/log/sip_6020.out /home/koha/koha-dev/var/log/sip_6020.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6021.xml /home/koha/koha-dev/var/log/sip_6021.out /home/koha/koha-dev/var/log/sip_6021.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6022.xml /home/koha/koha-dev/var/log/sip_6022.out /home/koha/koha-dev/var/log/sip_6022.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6023.xml /home/koha/koha-dev/var/log/sip_6023.out /home/koha/koha-dev/var/log/sip_6023.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6024.xml /home/koha/koha-dev/var/log/sip_6024.out /home/koha/koha-dev/var/log/sip_6024.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6025.xml /home/koha/koha-dev/var/log/sip_6025.out /home/koha/koha-dev/var/log/sip_6025.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6026.xml /home/koha/koha-dev/var/log/sip_6026.out /home/koha/koha-dev/var/log/sip_6026.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8023.xml /home/koha/koha-dev/var/log/sip_8023.out /home/koha/koha-dev/var/log/sip_8023.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8123.xml /home/koha/koha-dev/var/log/sip_8123.out /home/koha/koha-dev/var/log/sip_8123.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8223.xml /home/koha/koha-dev/var/log/sip_8223.out /home/koha/koha-dev/var/log/sip_8223.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8323.xml /home/koha/koha-dev/var/log/sip_8323.out /home/koha/koha-dev/var/log/sip_8323.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8423.xml /home/koha/koha-dev/var/log/sip_8423.out /home/koha/koha-dev/var/log/sip_8423.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8523.xml /home/koha/koha-dev/var/log/sip_8523.out /home/koha/koha-dev/var/log/sip_8523.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8623.xml /home/koha/koha-dev/var/log/sip_8623.out /home/koha/koha-dev/var/log/sip_8623.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8723.xml /home/koha/koha-dev/var/log/sip_8723.out /home/koha/koha-dev/var/log/sip_8723.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8823.xml /home/koha/koha-dev/var/log/sip_8823.out /home/koha/koha-dev/var/log/sip_8823.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8923.xml /home/koha/koha-dev/var/log/sip_8923.out /home/koha/koha-dev/var/log/sip_8923.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8924.xml /home/koha/koha-dev/var/log/sip_8924.out /home/koha/koha-dev/var/log/sip_8924.err
#/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8925.xml /home/koha/koha-dev/var/log/sip_8925.out /home/koha/koha-dev/var/log/sip_8925.err
#/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.8926.xml /home/koha/koha-dev/var/log/sip_8926.out /home/koha/koha-dev/var/log/sip_8926.err
