#!/bin/bash
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.xml /home/koha/koha-dev/var/log/sip_6001.out /home/koha/koha-dev/var/log/sip_6001.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6002.xml /home/koha/koha-dev/var/log/sip_6002.out /home/koha/koha-dev/var/log/sip_6002.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6003.xml /home/koha/koha-dev/var/log/sip_6003.out /home/koha/koha-dev/var/log/sip_6003.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6004.xml /home/koha/koha-dev/var/log/sip_6004.out /home/koha/koha-dev/var/log/sip_6004.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6005.xml /home/koha/koha-dev/var/log/sip_6005.out /home/koha/koha-dev/var/log/sip_6005.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6006.xml /home/koha/koha-dev/var/log/sip_6006.out /home/koha/koha-dev/var/log/sip_6006.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6007.xml /home/koha/koha-dev/var/log/sip_6007.out /home/koha/koha-dev/var/log/sip_6007.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6008.xml /home/koha/koha-dev/var/log/sip_6008.out /home/koha/koha-dev/var/log/sip_6008.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6009.xml /home/koha/koha-dev/var/log/sip_6009.out /home/koha/koha-dev/var/log/sip_6009.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6010.xml /home/koha/koha-dev/var/log/sip_6010.out /home/koha/koha-dev/var/log/sip_6010.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6011.xml /home/koha/koha-dev/var/log/sip_6011.out /home/koha/koha-dev/var/log/sip_6011.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6012.xml /home/koha/koha-dev/var/log/sip_6012.out /home/koha/koha-dev/var/log/sip_6012.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6013.xml /home/koha/koha-dev/var/log/sip_6013.out /home/koha/koha-dev/var/log/sip_6013.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6014.xml /home/koha/koha-dev/var/log/sip_6014.out /home/koha/koha-dev/var/log/sip_6014.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6015.xml /home/koha/koha-dev/var/log/sip_6015.out /home/koha/koha-dev/var/log/sip_6015.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6016.xml /home/koha/koha-dev/var/log/sip_6016.out /home/koha/koha-dev/var/log/sip_6016.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6017.xml /home/koha/koha-dev/var/log/sip_6017.out /home/koha/koha-dev/var/log/sip_6017.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6018.xml /home/koha/koha-dev/var/log/sip_6018.out /home/koha/koha-dev/var/log/sip_6018.err
/home/koha/kohaclone/C4/SIP/sip_run.sh ./SIPServer.6019.xml /home/koha/koha-dev/var/log/sip_6019.out /home/koha/koha-dev/var/log/sip_6019.err
